from typing import Protocol

from ..models import GameSettings, Question, UserProfile


class GameRepository(Protocol):
    """Future Firestore boundary for questions and configuration only."""
    def list_questions(self) -> list[Question]: ...
    def save_questions(self, questions: list[Question]) -> None: ...
    def get_settings(self) -> GameSettings | None: ...
    def save_settings(self, settings: GameSettings) -> None: ...
    def get_user(self, user_id: str) -> UserProfile | None: ...
    def save_user(self, profile: UserProfile) -> None: ...
    def list_users(self) -> list[UserProfile]: ...
    def delete_user(self, user_id: str) -> None: ...
