from typing import Callable, Protocol

from ..models import GameHistoryRecord, GameSettings, Question, RoomState, UserProfile


class RoomConflictError(RuntimeError):
    """The room changed after it was read and must be retried."""


class GameRepository(Protocol):
    """Persistent boundary for configuration, users, history, and live rooms."""
    def list_questions(self) -> list[Question]: ...
    def save_questions(self, questions: list[Question]) -> None: ...
    def get_settings(self) -> GameSettings | None: ...
    def save_settings(self, settings: GameSettings) -> None: ...
    def get_user(self, user_id: str) -> UserProfile | None: ...
    def save_user(self, profile: UserProfile) -> None: ...
    def list_users(self) -> list[UserProfile]: ...
    def delete_user(self, user_id: str) -> None: ...
    def save_game_history(self, user_id: str, record: GameHistoryRecord) -> None: ...
    def list_game_history(self, user_id: str) -> list[GameHistoryRecord]: ...
    def get_room(self, room_id: str) -> RoomState | None: ...
    def list_rooms(self) -> list[RoomState]: ...
    def save_room(self, room: RoomState, expected_version: int | None) -> RoomState: ...
    def delete_room(self, room_id: str, expected_version: int | None = None) -> None: ...
    def watch_rooms(self, callback: Callable[[str, RoomState | None], None]): ...
