from typing import Protocol

from ..models import GameSettings, Question


class GameRepository(Protocol):
    """Future Firestore boundary for questions and configuration only."""
    def list_questions(self) -> list[Question]: ...
    def save_questions(self, questions: list[Question]) -> None: ...
    def get_settings(self) -> GameSettings: ...
    def save_settings(self, settings: GameSettings) -> None: ...
